# ***Mount***

In [1]:
#Import google colab untuk meng-mount driva
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
!ls "/content/drive/My Drive"

# ***Sentimen 1***

In [16]:
!cp "/content/drive/My Drive/dataset/testpertama.csv" "testpertama.csv"

In [17]:
!ls

drive  resesi-indonesia3.csv  sample_data  testpertama.csv


In [18]:
#isi library yang diperlukan
import pandas as pd
import numpy as np

In [19]:
#Membaca file ke dalam dataframe dan mendeskripsikan isi data frame.....
dataabc = pd.read_csv('testpertama.csv')
dataabc.head(10)

Unnamed: 0                 Created_At      Tweet_Id         Username  \
0           0  2020-12-31 23:57:53+00:00  1.344795e+18        estitami5   
1           1  2020-12-31 23:55:39+00:00  1.344794e+18   Didiek09165668   
2           2  2020-12-31 23:54:05+00:00  1.344794e+18  SelamatBahagia2   
3           3  2020-12-31 23:49:50+00:00  1.344793e+18       Ekonomi4_0   
4           4  2020-12-31 23:49:20+00:00  1.344793e+18  LorrettaOmos531   
5           5  2020-12-31 23:46:11+00:00  1.344792e+18          KejatiK   
6           6  2020-12-31 23:45:14+00:00  1.344792e+18         idntimes   
7           7  2020-12-31 23:44:05+00:00  1.344791e+18        HokiKuaci   
8           8  2020-12-31 23:44:04+00:00  1.344791e+18       Ekonomi4_0   
9           9  2020-12-31 23:43:49+00:00  1.344791e+18     Lion33432792   

                                                Text Sentimen  
0  b'Semoga Undang-Undang Cipta Kerja Omnibus Law...  positif  
1  b'@wdtu Tentu perlu perjuangan panjang. Minima...  positif  
2  b'Markas Besar TNI perlu mengembangkan Industr...  positif  
3  b'Potensi ekonomi digital Indonesia perlu didu...  positif  
4  b'Kemudahan investasi dalam UU Cipta Kerja aka...  positif  
5  b'Jaksa Agung RI. ST, Burhanuddin\nMengucapkan...  positif  
6  b'Ekonomi Indonesia diyakini bangkit di 2021 h...  positif  
7  b'Iklim ramah investasi dan kemudahan berusaha...  positif  
8  b'Berkat UU Cipta Kerja, banyak investor globa...  positif  
9  b'Selamat tahun baru pak @jokowi \nSmg tahun i...  positif

In [21]:
dataabc.drop(columns = ['Unnamed: 0','Created_At','Tweet_Id','Username','Unnamed: 0'], inplace = True)
dataabc.head(5)

Text Sentimen
0  b'Semoga Undang-Undang Cipta Kerja Omnibus Law...  positif
1  b'@wdtu Tentu perlu perjuangan panjang. Minima...  positif
2  b'Markas Besar TNI perlu mengembangkan Industr...  positif
3  b'Potensi ekonomi digital Indonesia perlu didu...  positif
4  b'Kemudahan investasi dalam UU Cipta Kerja aka...  positif

In [22]:
# import
import csv
from google.colab import files
dataabc.to_csv('cleanabc.csv')
dataabc1 = pd.read_csv('cleanabc.csv')
dataabc1.head(5)

Unnamed: 0                                               Text Sentimen
0           0  b'Semoga Undang-Undang Cipta Kerja Omnibus Law...  positif
1           1  b'@wdtu Tentu perlu perjuangan panjang. Minima...  positif
2           2  b'Markas Besar TNI perlu mengembangkan Industr...  positif
3           3  b'Potensi ekonomi digital Indonesia perlu didu...  positif
4           4  b'Kemudahan investasi dalam UU Cipta Kerja aka...  positif

In [23]:
dataabc1.drop(columns = ['Unnamed: 0'], inplace = True)
dataabc1.head()

Text Sentimen
0  b'Semoga Undang-Undang Cipta Kerja Omnibus Law...  positif
1  b'@wdtu Tentu perlu perjuangan panjang. Minima...  positif
2  b'Markas Besar TNI perlu mengembangkan Industr...  positif
3  b'Potensi ekonomi digital Indonesia perlu didu...  positif
4  b'Kemudahan investasi dalam UU Cipta Kerja aka...  positif

In [24]:
print(dataabc.shape)
dataabc.duplicated().sum()

(2303, 2)


24

In [25]:
#import library yang dibutuhkan
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.feature_extraction.text import CountVectorizer
import nltk
import string
import re

In [26]:
import re
from bs4 import BeautifulSoup
from nltk.tokenize import WordPunctTokenizer

tokenizer = WordPunctTokenizer()
twitter_handle = r'@[A-Za-z0-9_]+'                         # remove twitter handle (@username)
url_handle = r'http[^ ]+'                                  # remove website URLs that start with 'https?://'
combined_handle = r'|'.join((twitter_handle, url_handle))  # join
www_handle = r'www.[^ ]+'                                  # remove website URLs that start with 'www.'
punctuation_handle = r'\W+'

In [31]:
stopwords = set(pd.read_csv('/content/drive/My Drive//kuliah/TA/stopwordskosong.txt', header=0).stopword)

In [32]:
def process_text(text):
    soup = BeautifulSoup(text, 'lxml')
    souped = soup.get_text()

    try:
        text = souped.decode("utf-8-sig").replace(u"\ufffd", "?")
    except:
        text = souped

    cleaned_text = re.sub(punctuation_handle, " ",(re.sub(www_handle, '', re.sub(combined_handle, '', text)).lower()))
    cleaned_text = ' '.join([word for word in cleaned_text.split() if word not in stopwords])

    return (" ".join([word for word in tokenizer.tokenize(cleaned_text) if len(word) > 1])).strip()

In [33]:
cleaned_text = []

for text in dataabc1.Text:
    cleaned_text.append(process_text(text))

clean_text = pd.DataFrame({'text1' : cleaned_text})
dataabc1 = pd.concat([dataabc1, clean_text], axis = 1)
dataabc1.head(6)

<ipython-input-32-b7d1d2404d7d>:2: MarkupResemblesLocatorWarning: The input looks more like a filename than markup. You may want to open this file and pass the filehandle into Beautiful Soup.
  soup = BeautifulSoup(text, 'lxml')


Text Sentimen  \
0  b'Semoga Undang-Undang Cipta Kerja Omnibus Law...  positif   
1  b'@wdtu Tentu perlu perjuangan panjang. Minima...  positif   
2  b'Markas Besar TNI perlu mengembangkan Industr...  positif   
3  b'Potensi ekonomi digital Indonesia perlu didu...  positif   
4  b'Kemudahan investasi dalam UU Cipta Kerja aka...  positif   
5  b'Jaksa Agung RI. ST, Burhanuddin\nMengucapkan...  positif   

                                               text1  
0  semoga undang undang cipta kerja omnibus law b...  
1  tentu perlu perjuangan panjang minimal peningk...  
2  markas besar tni perlu mengembangkan industri ...  
3  potensi ekonomi digital indonesia perlu diduku...  
4  kemudahan investasi dalam uu cipta kerja akan ...  
5  jaksa agung ri st burhanuddin nmengucapkan nse...

In [34]:
#library yang diperlukan
!pip install Sastrawi
!pip install nltk
nltk.download("popular")

#Import library yang dibutuhkan dalam proses preprocessing
import string #library untuk bekerja dengan text
import re #regex library
#import itertools #Library iterator untuk perulangan yang efisien
import nltk #library yang merupakan bagian dari NLP yang untuk bekerja dengan pemodelan teks
from nltk.tokenize import word_tokenize #import library package untuk proses Tokenisasi
from Sastrawi.Stemmer.StemmerFactory import StemmerFactory #import library package untuk proses Stemming
from nltk.corpus import stopwords #import library package untuk proses Stopwords
#from Sastrawi.StopWordRemover.StopWordRemoverFactory import StopWordRemoverFactory, StopWordRemover, ArrayDictionary


[nltk_data] Downloading collection 'popular'
[nltk_data]    | 
[nltk_data]    | Downloading package cmudict to /root/nltk_data...
[nltk_data]    |   Package cmudict is already up-to-date!
[nltk_data]    | Downloading package gazetteers to /root/nltk_data...
[nltk_data]    |   Package gazetteers is already up-to-date!
[nltk_data]    | Downloading package genesis to /root/nltk_data...
[nltk_data]    |   Package genesis is already up-to-date!
[nltk_data]    | Downloading package gutenberg to /root/nltk_data...
[nltk_data]    |   Package gutenberg is already up-to-date!
[nltk_data]    | Downloading package inaugural to /root/nltk_data...
[nltk_data]    |   Package inaugural is already up-to-date!
[nltk_data]    | Downloading package movie_reviews to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Package movie_reviews is already up-to-date!
[nltk_data]    | Downloading package names to /root/nltk_data...
[nltk_data]    |   Package names is already up-to-date!
[nltk_data]    | Do

In [35]:
# ------ Case Folding --------
#Digunakan untuk transform huruf menjadi huruf lower atau kecil agar seragam
dataabc1['sentiment_text'] = dataabc1['text1'].str.lower()

print('Case Folding Result : \n')
print(dataabc1['sentiment_text'].head(20))
print('\n\n\n')

#Fungsi yang digunakan untuk mengganti atau menghapus karakter yang spesial, hal ini dibutuhkan sebagai bentuk menyamakan pola tulisan agar seragam dan mudah dibaca
def remove_text_special(sentiment_text):
    #hapus tab, new line, and back slice
    sentiment_text = sentiment_text.replace('\\t'," ").replace('\\n'," ").replace('\\u'," ").replace('\\',"").replace('\x80¦',"")
    #hapus non ASCII (emoticon, chinese word, dll)
    sentiment_text = sentiment_text.encode('ascii', 'replace').decode('ascii')
    return sentiment_text

dataabc1['sentiment_text'] = dataabc1['sentiment_text'].apply(remove_text_special)

#hapus emoji ✍ 🌷 📌 👈🏻 🖥
"""
Pada tahapan ini prosesnya dengan meng compile kode emoticon tersebut lalu replace kode tersebut dengan karakter kosong, kode kode tersebut didapatkan dari sumber referensi internet
"""
def remove_emoji(sentiment_text):
    emoji_pattern = re.compile("["
                           u"\U0001F600-\U0001F64F"  # emoticons
                           u"\U0001F300-\U0001F5FF"  # symbols & pictographs
                           u"\U0001F680-\U0001F6FF"  # transport & map symbols
                           u"\U0001F1E0-\U0001F1FF"  # flags (iOS)
                           u"\U00002500-\U00002BEF"  # chinese char
                           u"\U00002702-\U000027B0"
                           u"\U00002702-\U000027B0"
                           u"\U000024C2-\U0001F251"
                           u"\U0001f926-\U0001f937"
                           u"\U00010000-\U0010ffff"
                           u"\u2640-\u2642"
                           u"\u2600-\u2B55"
                           u"\u200d"
                           u"\u23cf"
                           u"\u23e9"
                           u"\u231a"
                           u"\ufe0f"  # dingbats
                           u"\u3030"
                               #mengonversi data input ke Unicode
                           "]+", flags=re.UNICODE)
    return emoji_pattern.sub(r'', sentiment_text)

dataabc1['sentiment_text'] = dataabc1['sentiment_text'].apply(remove_emoji)

Case Folding Result : 

0     semoga undang undang cipta kerja omnibus law b...
1     tentu perlu perjuangan panjang minimal peningk...
2     markas besar tni perlu mengembangkan industri ...
3     potensi ekonomi digital indonesia perlu diduku...
4     kemudahan investasi dalam uu cipta kerja akan ...
5     jaksa agung ri st burhanuddin nmengucapkan nse...
6            ekonomi indonesia diyakini bangkit di 2021
7     iklim ramah investasi dan kemudahan berusaha u...
8     berkat uu cipta kerja banyak investor global t...
9     selamat tahun baru pak nsmg tahun ini ekonomi ...
10    pemerintah menargetkan indonesia xc2 xa0masuk ...
11    mi instan asal indonesia jadi alat transaksi s...
12    kami menyampaikan selamat tahun baru 2021 kira...
13    teknologi informasi dan komunikasi tik adalah ...
14    harapanku di tahun 2021 nindonesia bebas koron...
15    teknologi informasi dan komunikasi tik adalah ...
16    berharap implementasi uu ini segera dilakukan ...
17    era new umkm ini d

In [36]:
import nltk
nltk.download('punkt')

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!


True

In [41]:
slangwords = set(pd.read_csv('/content/drive/My Drive/kuliah/TA/slangword.txt', header=0, error_bad_lines=False).slangword)

<ipython-input-41-15696be80f2f>:1: FutureWarning: The error_bad_lines argument has been deprecated and will be removed in a future version. Use on_bad_lines in the future.


  slangwords = set(pd.read_csv('/content/drive/My Drive/kuliah/TA/slangword.txt', header=0, error_bad_lines=False).slangword)
Skipping line 86: expected 1 fields, saw 4
Skipping line 617: expected 1 fields, saw 4
Skipping line 713: expected 1 fields, saw 4
Skipping line 715: expected 1 fields, saw 3
Skipping line 824: expected 1 fields, saw 2



In [42]:
def word_tokenize_wrapper(sentiment_text):
    tokens = word_tokenize(sentiment_text)

    #proses normalization menghilangkan Slang Words dari dict appos yang sebelumnya sudah dibuat
    reformed = [slangwords[word] if word in slangwords else word for word in tokens]
    table = str.maketrans('', '', string.punctuation)
    stripped = [w.translate(table) for w in reformed]
    words = [word for word in stripped if word.isalpha()]
    return words

dataabc1['sentiment_text'] = dataabc1['sentiment_text'].apply(word_tokenize_wrapper)


print('Tokenizing Result : \n')
print(dataabc1['sentiment_text'].head(20))
print('\n\n\n')

"""
Fungsi negation handling digunakan untuk membalikkan polaritas kata kata yang mempengaruhi orientasi sentimen kata lain dalam sebuah kalimat dengan mengubah arti kata tersebut menjadi makna yang sebenarnya. Proses Negation Handling yang dimana setelah di tokenisasi dan koreksi setiap tata Bahasa kata selanjutnya dilakukan proses ini untuk membuat arti dari setiap kata tidak salah makna.
"""
def negation_handling(sentiment_text):
    negation_sentiment_text = []
    for i in range(len(sentiment_text)):
        word = sentiment_text[i]
        if sentiment_text[i-1] not in ['tidak','kurang','tak','tanpa','terlalu','bukan','belum']:
            negation_sentiment_text.append(word)
        else:
            word = "%s_%s" %(sentiment_text[i-1],word)
            negation_sentiment_text.append(word)
    return negation_sentiment_text

dataabc1['sentiment_text'] = dataabc1['sentiment_text'].apply(negation_handling)
print('Negation Result : \n')
print(dataabc1['sentiment_text'].head(20))
print('\n\n\n')


Tokenizing Result : 

0     [semoga, undang, undang, cipta, kerja, omnibus...
1     [tentu, perlu, perjuangan, panjang, minimal, p...
2     [markas, besar, tni, perlu, mengembangkan, ind...
3     [potensi, ekonomi, digital, indonesia, perlu, ...
4     [kemudahan, investasi, dalam, uu, cipta, kerja...
5     [jaksa, agung, ri, st, burhanuddin, nmengucapk...
6           [ekonomi, indonesia, diyakini, bangkit, di]
7     [iklim, ramah, investasi, dan, kemudahan, beru...
8     [berkat, uu, cipta, kerja, banyak, investor, g...
9     [selamat, tahun, baru, pak, nsmg, tahun, ini, ...
10    [pemerintah, menargetkan, indonesia, dalam, li...
11    [mi, instan, asal, indonesia, jadi, alat, tran...
12    [kami, menyampaikan, selamat, tahun, baru, kir...
13    [teknologi, informasi, dan, komunikasi, tik, a...
14    [harapanku, di, tahun, nindonesia, bebas, koro...
15    [teknologi, informasi, dan, komunikasi, tik, a...
16    [berharap, implementasi, uu, ini, segera, dila...
17    [era, new, umkm, ini

In [43]:
factory = StemmerFactory() #Variabel factory berisi class untuk proses stemming dari library stemming
stemmer = factory.create_stemmer() #Variabel stemmer digunakan untuk mengambil fungsi pembuatan stemming dari class StemmerFactory()

#fungsi untuk proses stemming
def stemmed_wrapper(term):
  return stemmer.stem(term)

#variabel untuk menampung dictionary dari kata-kata term stemming
term_dict = {}

"""
Proses iterasi untuk pembuatan dict termnya, yang dimana akan dilakukan pengecekan kata kata hasil dari proses tokenisasi, Jadi setelah di tokenisasi, kemudian semua kata-kata tersebut akan ditampung di dalam term_dict yang dimana nantinya kata-kata  tersebut akan melalui proses dari fungsi stemming. Jika kata tersebut bukan termasuk di variabel term_dict maka list kata di  dictionary tersebut akan dikosongkan.
"""
for document in dataabc1['sentiment_text']:
  for term in document:
    if term not in term_dict:
      term_dict[term] = " "

print(len(term_dict))
print("------------------------------")

"""
proses iterasi untuk pengecekan setiap kata di dalam variabel term_dict, yang kemudian di dalam proses tersebut terjadinya proses perubahan setiap kata yang akan dilakukan oleh fungsi stemmed_wrapper yang berisi proses stemming kata. Setelah itu,
akan ditampilkan hasil dari proses perubahan.
"""
for term in term_dict:
  term_dict[term] = stemmed_wrapper(term)
  print(term,":",term_dict[term])

#print(term_dict)
print("-----------------------------")

"""
Kemudian hasil perubahan stemmingnya dimasukkan ke dalam dataframe untuk diolah ke tahapan berikutnya
"""
def get_stemmed_term(document):
  return[term_dict[term] for term in document]

dataabc1['sentiment_text'] = dataabc1['sentiment_text'].apply(get_stemmed_term)
print(dataabc1['sentiment_text'])


Streaming output truncated to the last 5000 lines.
fenomena : fenomena
singkawang : singkawang
berjuluk : juluk
webminar : webminar
npemulihan : npemulihan
ekonomu : ekonomu
bukan_nya : bukan nya
sejenis : jenis
diksh : diksh
promo : promo
kpn : kpn
memalukan : malu
sensitive : sensitive
berutang : utang
menaikkan : naik
tidak_malu : tidak malu
rcep : rcep
katalis : katalis
berkualitas : kualitas
bunghattamuda : bunghattamuda
kampusproklamator : kampusproklamator
masukkampus : masukkampus
pendidikanuntukkerja : pendidikanuntukkerja
mahasiswaindonesia : mahasiswaindonesia
mahasiswi : mahasiswi
bukti : bukti
tak_menguntungkan : tak untung
nelayan : nelayan
kalah : kalah
mantap : mantap
nich : nich
strategis : strategis
infosaham : infosaham
hargasaham : hargasaham
kecerdasan : cerdas
maaruf : maaruf
diasia : diasia
nmakanya : nmakanya
ngurusi : ngurusi
urus : urus
tuh : tuh
modus : modus
edhy : edhy
prabowo : prabowo
terciduk : ciduk
kpk : kpk
mesti : mesti
tragedi : tragedi
sigi : sigi


In [44]:
dataabc1.head(10)

Text Sentimen  \
0  b'Semoga Undang-Undang Cipta Kerja Omnibus Law...  positif   
1  b'@wdtu Tentu perlu perjuangan panjang. Minima...  positif   
2  b'Markas Besar TNI perlu mengembangkan Industr...  positif   
3  b'Potensi ekonomi digital Indonesia perlu didu...  positif   
4  b'Kemudahan investasi dalam UU Cipta Kerja aka...  positif   
5  b'Jaksa Agung RI. ST, Burhanuddin\nMengucapkan...  positif   
6  b'Ekonomi Indonesia diyakini bangkit di 2021 h...  positif   
7  b'Iklim ramah investasi dan kemudahan berusaha...  positif   
8  b'Berkat UU Cipta Kerja, banyak investor globa...  positif   
9  b'Selamat tahun baru pak @jokowi \nSmg tahun i...  positif   

                                               text1  \
0  semoga undang undang cipta kerja omnibus law b...   
1  tentu perlu perjuangan panjang minimal peningk...   
2  markas besar tni perlu mengembangkan industri ...   
3  potensi ekonomi digital indonesia perlu diduku...   
4  kemudahan investasi dalam uu cipta kerja akan ...   
5  jaksa agung ri st burhanuddin nmengucapkan nse...   
6         ekonomi indonesia diyakini bangkit di 2021   
7  iklim ramah investasi dan kemudahan berusaha u...   
8  berkat uu cipta kerja banyak investor global t...   
9  selamat tahun baru pak nsmg tahun ini ekonomi ...   

                                      sentiment_text  
0  [moga, undang, undang, cipta, kerja, omnibus, ...  
1  [tentu, perlu, juang, panjang, minimal, tingka...  
2  [markas, besar, tni, perlu, kembang, industri,...  
3  [potensi, ekonomi, digital, indonesia, perlu, ...  
4  [mudah, investasi, dalam, uu, cipta, kerja, ak...  
5  [jaksa, agung, ri, st, burhanuddin, nmengucapk...  
6           [ekonomi, indonesia, yakin, bangkit, di]  
7  [iklim, ramah, investasi, dan, mudah, usaha, u...  
8  [berkat, uu, cipta, kerja, banyak, investor, g...  
9  [selamat, tahun, baru, pak, nsmg, tahun, ini, ...

In [45]:
#import stopword
from nltk.corpus import stopwords
stopwords_indonesia = stopwords.words('indonesian')

#import sastrawi
from Sastrawi.Stemmer.StemmerFactory import StemmerFactory
factory = StemmerFactory()
stemmer = factory.create_stemmer()

#tokenize
from nltk.tokenize import TweetTokenizer

# Happy Emoticons
emoticons_happy = set([
    ':-)', ':)', ';)', ':o)', ':]', ':3', ':c)', ':>', '=]', '8)', '=)', ':}',
    ':^)', ':-D', ':D', '8-D', '8D', 'x-D', 'xD', 'X-D', 'XD', '=-D', '=D',
    '=-3', '=3', ':-))', ":'-)", ":')", ':*', ':^*', '>:P', ':-P', ':P', 'X-P',
    'x-p', 'xp', 'XP', ':-p', ':p', '=p', ':-b', ':b', '>:)', '>;)', '>:-)',
    '<3'
    ])

# Sad Emoticons
emoticons_sad = set([
    ':L', ':-/', '>:/', ':S', '>:[', ':@', ':-(', ':[', ':-||', '=L', ':<',
    ':-[', ':-<', '=\\', '=/', '>:(', ':(', '>.<', ":'-(", ":'(", ':\\', ':-c',
    ':c', ':{', '>:\\', ';('
    ])

# all emoticons (happy + sad)
emoticons = emoticons_happy.union(emoticons_sad)

def clean_tweets(tweet):
    # remove stock market tickers like $GE
    tweet = re.sub(r'\$\w*', '', tweet)

    # remove old style retweet text "RT"
    tweet = re.sub(r'^RT[\s]+', '', tweet)

    # remove hyperlinks
    tweet = re.sub(r'https?:\/\/.*[\r\n]*', '', tweet)

    # remove hashtags
    # only removing the hash # sign from the word
    tweet = re.sub(r'#', '', tweet)

    #remove coma
    tweet = re.sub(r',','',tweet)

    #remove angka
    tweet = re.sub('[0-9]+', '', tweet)

    # tokenize tweets
    tokenizer = TweetTokenizer(preserve_case=False, strip_handles=True, reduce_len=True)
    tweet_tokens = tokenizer.tokenize(tweet)

    tweets_clean = []
    for word in tweet_tokens:
        if (word not in stopwords_indonesia and # remove stopwords
              word not in emoticons and # remove emoticons
                word not in string.punctuation): # remove punctuation
            #tweets_clean.append(word)
            stem_word = stemmer.stem(word) # stemming word
            tweets_clean.append(stem_word)

    return tweets_clean

In [46]:
df  = pd.DataFrame(dataabc1[['sentiment_text','Sentimen','text1','Text']])#ubah dataframe sesuai column kalian

In [47]:
df

sentiment_text Sentimen  \
0     [moga, undang, undang, cipta, kerja, omnibus, ...  positif   
1     [tentu, perlu, juang, panjang, minimal, tingka...  positif   
2     [markas, besar, tni, perlu, kembang, industri,...  positif   
3     [potensi, ekonomi, digital, indonesia, perlu, ...  positif   
4     [mudah, investasi, dalam, uu, cipta, kerja, ak...  positif   
...                                                 ...      ...   
2298  [new, normal, harus, laku, demi, pulih, aktifi...  positif   
2299  [minta, kurang, usaha, pasti, logistik, laut, ...  positif   
2300  [ekonomi, indonesia, makin, baik, dan, maju, d...  positif   
2301  [untung, indonesia, milik, menteri, yang, kere...  positif   
2302  [hatarajasa, ekonomi, indonesia, masih, prihat...  negatif   

                                                  text1  \
0     semoga undang undang cipta kerja omnibus law b...   
1     tentu perlu perjuangan panjang minimal peningk...   
2     markas besar tni perlu mengembangkan industri ...   
3     potensi ekonomi digital indonesia perlu diduku...   
4     kemudahan investasi dalam uu cipta kerja akan ...   
...                                                 ...   
2298  new normal harus dilakukan demi pulihnya aktif...   
2299  permintaan berkurang pengusaha pastikan logist...   
2300  ekonomi indonesia semakin baik dan maju dengan...   
2301  untung indonesia memiliki menteri yang keren i...   
2302  hatarajasa ekonomi indonesia masih memprihatin...   

                                                   Text  
0     b'Semoga Undang-Undang Cipta Kerja Omnibus Law...  
1     b'@wdtu Tentu perlu perjuangan panjang. Minima...  
2     b'Markas Besar TNI perlu mengembangkan Industr...  
3     b'Potensi ekonomi digital Indonesia perlu didu...  
4     b'Kemudahan investasi dalam UU Cipta Kerja aka...  
...                                                 ...  
2298  b'New Normal harus dilakukan demi pulihnya akt...  
2299  b'Permintaan Berkurang, Pengusaha Pastikan Log...  
2300  b'Ekonomi Indonesia semakin baik dan maju deng...  
2301  b'Untung Indonesia memiliki menteri yang keren...  
2302  b'Hatarajasa : Ekonomi Indonesia Masih Memprih...  

[2303 rows x 4 columns]

In [48]:
df['tweet_clean'] = df['text1'].apply(lambda x: clean_tweets(x))

In [49]:
df

sentiment_text Sentimen  \
0     [moga, undang, undang, cipta, kerja, omnibus, ...  positif   
1     [tentu, perlu, juang, panjang, minimal, tingka...  positif   
2     [markas, besar, tni, perlu, kembang, industri,...  positif   
3     [potensi, ekonomi, digital, indonesia, perlu, ...  positif   
4     [mudah, investasi, dalam, uu, cipta, kerja, ak...  positif   
...                                                 ...      ...   
2298  [new, normal, harus, laku, demi, pulih, aktifi...  positif   
2299  [minta, kurang, usaha, pasti, logistik, laut, ...  positif   
2300  [ekonomi, indonesia, makin, baik, dan, maju, d...  positif   
2301  [untung, indonesia, milik, menteri, yang, kere...  positif   
2302  [hatarajasa, ekonomi, indonesia, masih, prihat...  negatif   

                                                  text1  \
0     semoga undang undang cipta kerja omnibus law b...   
1     tentu perlu perjuangan panjang minimal peningk...   
2     markas besar tni perlu mengembangkan industri ...   
3     potensi ekonomi digital indonesia perlu diduku...   
4     kemudahan investasi dalam uu cipta kerja akan ...   
...                                                 ...   
2298  new normal harus dilakukan demi pulihnya aktif...   
2299  permintaan berkurang pengusaha pastikan logist...   
2300  ekonomi indonesia semakin baik dan maju dengan...   
2301  untung indonesia memiliki menteri yang keren i...   
2302  hatarajasa ekonomi indonesia masih memprihatin...   

                                                   Text  \
0     b'Semoga Undang-Undang Cipta Kerja Omnibus Law...   
1     b'@wdtu Tentu perlu perjuangan panjang. Minima...   
2     b'Markas Besar TNI perlu mengembangkan Industr...   
3     b'Potensi ekonomi digital Indonesia perlu didu...   
4     b'Kemudahan investasi dalam UU Cipta Kerja aka...   
...                                                 ...   
2298  b'New Normal harus dilakukan demi pulihnya akt...   
2299  b'Permintaan Berkurang, Pengusaha Pastikan Log...   
2300  b'Ekonomi Indonesia semakin baik dan maju deng...   
2301  b'Untung Indonesia memiliki menteri yang keren...   
2302  b'Hatarajasa : Ekonomi Indonesia Masih Memprih...   

                                            tweet_clean  
0     [moga, undang, undang, cipta, kerja, omnibus, ...  
1     [juang, minimal, tingkat, didik, pelosok, dg, ...  
2     [markas, tni, kembang, industri, militer, penu...  
3     [potensi, ekonomi, digital, indonesia, dukung,...  
4     [mudah, investasi, uu, cipta, kerja, maju, eko...  
...                                                 ...  
2298  [new, normal, pulih, aktifitas, ekonomi, indon...  
2299  [minta, kurang, usaha, pasti, logistik, laut, ...  
2300  [ekonomi, indonesia, maju, dukung, ada, omnibu...  
2301  [untung, indonesia, milik, menteri, keren, cob...  
2302  [hatarajasa, ekonomi, indonesia, prihatin, hat...  

[2303 rows x 5 columns]

In [50]:
df.drop(columns = ['text1','sentiment_text','Text'], inplace = True)
df.head(10)

Sentimen                                        tweet_clean
0  positif  [moga, undang, undang, cipta, kerja, omnibus, ...
1  positif  [juang, minimal, tingkat, didik, pelosok, dg, ...
2  positif  [markas, tni, kembang, industri, militer, penu...
3  positif  [potensi, ekonomi, digital, indonesia, dukung,...
4  positif  [mudah, investasi, uu, cipta, kerja, maju, eko...
5  positif  [jaksa, agung, ri, st, burhanuddin, nmengucapk...
6  positif               [ekonomi, indonesia, yakin, bangkit]
7  positif  [iklim, ramah, investasi, mudah, usaha, uu, ci...
8  positif  [berkat, uu, cipta, kerja, investor, global, t...
9  positif  [selamat, nsmg, ekonomi, bangsa, indonesia, lg...

In [51]:
df.to_csv('data1.csv',encoding='utf8', index=False)
dataabcd1 = pd.read_csv('data1.csv')
dataabcd1.head(20)

Sentimen                                        tweet_clean
0   positif  ['moga', 'undang', 'undang', 'cipta', 'kerja',...
1   positif  ['juang', 'minimal', 'tingkat', 'didik', 'pelo...
2   positif  ['markas', 'tni', 'kembang', 'industri', 'mili...
3   positif  ['potensi', 'ekonomi', 'digital', 'indonesia',...
4   positif  ['mudah', 'investasi', 'uu', 'cipta', 'kerja',...
5   positif  ['jaksa', 'agung', 'ri', 'st', 'burhanuddin', ...
6   positif       ['ekonomi', 'indonesia', 'yakin', 'bangkit']
7   positif  ['iklim', 'ramah', 'investasi', 'mudah', 'usah...
8   positif  ['berkat', 'uu', 'cipta', 'kerja', 'investor',...
9   positif  ['selamat', 'nsmg', 'ekonomi', 'bangsa', 'indo...
10  positif  ['perintah', 'target', 'indonesia', 'xc', 'xam...
11  negatif  ['mi', 'instan', 'indonesia', 'alat', 'transak...
12  positif  ['selamat', 'tuhan', 'rahmat', 'hikmat', 'seha...
13  positif  ['teknologi', 'informasi', 'komunikasi', 'tik'...
14  positif  ['harap', 'nindonesia', 'bebas', 'korona', 'ns...
15  positif  ['teknologi', 'informasi', 'komunikasi', 'tik'...
16  positif  ['harap', 'implementasi', 'uu', 'bijak', 'targ...
17  positif  ['era', 'new', 'umkm', 'harap', 'sumber', 'tum...
18  negatif  ['tangkap', 'yg', 'nyalain', 'kembang', 'api',...
19  positif  ['bangkit', 'ekonomi', 'indonesia', 'kembangka...

In [52]:
print(dataabcd1.shape)
dataabcd1.duplicated().sum()


(2303, 2)


357

In [53]:
#menghapus entri yang memiliki data duplikat
dataabcd1.drop_duplicates(inplace=True)
print(dataabcd1.duplicated().sum()) # no more duplicates
print(dataabcd1.shape) # re-check by printing data size

0
(1946, 2)


In [54]:
dataabcd1.isnull().sum() # semua kolom

Sentimen       0
tweet_clean    0
dtype: int64

In [55]:
dataabcd1.dropna(inplace=True)
dataabcd1.isnull().sum()

Sentimen       0
tweet_clean    0
dtype: int64

In [56]:
dataabcd1.to_csv('dataabcd2.csv')
dataabcd2 = pd.read_csv('dataabcd2.csv')
dataabcd2.drop(columns = ['Unnamed: 0'], inplace = True)
dataabcd2.head(6)

Sentimen                                        tweet_clean
0  positif  ['moga', 'undang', 'undang', 'cipta', 'kerja',...
1  positif  ['juang', 'minimal', 'tingkat', 'didik', 'pelo...
2  positif  ['markas', 'tni', 'kembang', 'industri', 'mili...
3  positif  ['potensi', 'ekonomi', 'digital', 'indonesia',...
4  positif  ['mudah', 'investasi', 'uu', 'cipta', 'kerja',...
5  positif  ['jaksa', 'agung', 'ri', 'st', 'burhanuddin', ...

# ***Model Evaluation 1***

In [57]:
dataabcd2.to_csv('testabc.csv')
dataabcd2 = pd.read_csv('testabc.csv')

In [58]:
dataabcd2['Sentimen'].replace({'positif': 1, 'negatif': 0}, inplace=True)

In [59]:
dataabcd2['Sentimen'].value_counts()

1    1319
0     627
Name: Sentimen, dtype: int64

In [60]:
# Memisahkan kelas majority dan minority
df_maj = dataabcd2[dataabcd2.Sentimen==1]
df_min = dataabcd2[dataabcd2.Sentimen==0]

In [61]:
# downsample minority class // metode untung resampling menyesuaikan data sebanyak data majority

from sklearn.utils import resample
df_min_dwsampled = resample(df_maj,
                                 replace=True,     # sample with replacement
                                 n_samples=627,    # to match majority class
                                 random_state=123) # reproducible results

# Combine majority class with upsampled minority class
df_dwsampled = pd.concat([df_min, df_min_dwsampled])

# Display new class counts
df_dwsampled.Sentimen.value_counts()

0    627
1    627
Name: Sentimen, dtype: int64

In [62]:
from sklearn.pipeline import Pipeline
from sklearn.feature_extraction.text import CountVectorizer, TfidfTransformer, TfidfVectorizer
from sklearn.model_selection import train_test_split, GridSearchCV

#Import classification algorithm
from sklearn.naive_bayes import MultinomialNB
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import LinearSVC
from sklearn.ensemble import RandomForestClassifier

#Import modules to calculate accuracy and confusion matrix
from sklearn.metrics import confusion_matrix, accuracy_score
from sklearn.metrics import classification_report

In [63]:
text_clf = Pipeline([('vect', CountVectorizer()),
                     ('tfidf', TfidfTransformer()),
                     ('clf', MultinomialNB())])
tuned_parameters = {
    'vect__ngram_range': [(1, 1), (1, 2), (2, 2)],
    'tfidf__use_idf': (True, False),
    'tfidf__norm': ('l1', 'l2'),
    'clf__alpha': [1, 1e-1, 1e-2]
}

In [64]:
text_clf5 = Pipeline([('vect', CountVectorizer()),
                     ('tfidf', TfidfTransformer()),
                     ('clf5', LinearSVC())])
tuned_parameters5 = {


}

In [65]:
text_clf3 = Pipeline([('vect', CountVectorizer()),
                     ('tfidf', TfidfTransformer()),
                     ('clf3', KNeighborsClassifier())])
tuned_parameters3 = {

}

In [66]:
x_train, x_test, y_train, y_test = train_test_split(df_dwsampled['tweet_clean'], df_dwsampled['Sentimen'],
                                              shuffle=True)

In [67]:
clf = GridSearchCV(text_clf, tuned_parameters, cv=10)
clf.fit(x_train, y_train)

print(classification_report(y_test, clf.predict(x_test), digits=4))
print(accuracy_score(y_test, clf.predict(x_test)))
print(confusion_matrix(y_test, clf.predict(x_test)))
print('--------------------------------------------------------------------')


clf = GridSearchCV(text_clf, tuned_parameters, cv=10)
clf.fit(x_train, y_train)

print(classification_report(y_test, clf.predict(x_test), digits=4))
print(accuracy_score(y_test, clf.predict(x_test)))
print(confusion_matrix(y_test, clf.predict(x_test)))
print('--------------------------------------------------------------------')


clf = GridSearchCV(text_clf, tuned_parameters, cv=10)
clf.fit(x_train, y_train)

print(classification_report(y_test, clf.predict(x_test), digits=4))
print(accuracy_score(y_test, clf.predict(x_test)))
print(confusion_matrix(y_test, clf.predict(x_test)))

              precision    recall  f1-score   support

           0     0.8301    0.7791    0.8038       163
           1     0.7764    0.8278    0.8013       151

    accuracy                         0.8025       314
   macro avg     0.8032    0.8035    0.8025       314
weighted avg     0.8043    0.8025    0.8026       314

0.802547770700637
[[127  36]
 [ 26 125]]
--------------------------------------------------------------------
              precision    recall  f1-score   support

           0     0.8301    0.7791    0.8038       163
           1     0.7764    0.8278    0.8013       151

    accuracy                         0.8025       314
   macro avg     0.8032    0.8035    0.8025       314
weighted avg     0.8043    0.8025    0.8026       314

0.802547770700637
[[127  36]
 [ 26 125]]
--------------------------------------------------------------------
              precision    recall  f1-score   support

           0     0.8301    0.7791    0.8038       163
           1     

In [68]:
clf5 = GridSearchCV(text_clf5, tuned_parameters5, cv=10)
clf5.fit(x_train, y_train)

print(classification_report(y_test, clf5.predict(x_test), digits=4))
print(accuracy_score(y_test, clf5.predict(x_test)))
print(confusion_matrix(y_test, clf5.predict(x_test)))
print('--------------------------------------------------------------------')


clf5 = GridSearchCV(text_clf5, tuned_parameters5, cv=10)
clf5.fit(x_train, y_train)

print(classification_report(y_test, clf5.predict(x_test), digits=4))
print(accuracy_score(y_test, clf5.predict(x_test)))
print(confusion_matrix(y_test, clf5.predict(x_test)))
print('--------------------------------------------------------------------')



clf5 = GridSearchCV(text_clf5, tuned_parameters5, cv=10)
clf5.fit(x_train, y_train)

print(classification_report(y_test, clf5.predict(x_test), digits=4))
print(accuracy_score(y_test, clf5.predict(x_test)))
print(confusion_matrix(y_test, clf5.predict(x_test)))

              precision    recall  f1-score   support

           0     0.8269    0.7914    0.8088       163
           1     0.7848    0.8212    0.8026       151

    accuracy                         0.8057       314
   macro avg     0.8059    0.8063    0.8057       314
weighted avg     0.8067    0.8057    0.8058       314

0.8057324840764332
[[129  34]
 [ 27 124]]
--------------------------------------------------------------------
              precision    recall  f1-score   support

           0     0.8269    0.7914    0.8088       163
           1     0.7848    0.8212    0.8026       151

    accuracy                         0.8057       314
   macro avg     0.8059    0.8063    0.8057       314
weighted avg     0.8067    0.8057    0.8058       314

0.8057324840764332
[[129  34]
 [ 27 124]]
--------------------------------------------------------------------
              precision    recall  f1-score   support

           0     0.8269    0.7914    0.8088       163
           1   

In [69]:
clf3 = GridSearchCV(text_clf3, tuned_parameters3, cv=10)
clf3.fit(x_train, y_train)

print(classification_report(y_test, clf3.predict(x_test), digits=4))
print(accuracy_score(y_test, clf3.predict(x_test)))
print(confusion_matrix(y_test, clf3.predict(x_test)))
print('--------------------------------------------------------------------')

clf3 = GridSearchCV(text_clf3, tuned_parameters3, cv=10)
clf3.fit(x_train, y_train)

print(classification_report(y_test, clf3.predict(x_test), digits=4))
print(accuracy_score(y_test, clf3.predict(x_test)))
print(confusion_matrix(y_test, clf3.predict(x_test)))
print('--------------------------------------------------------------------')

clf3 = GridSearchCV(text_clf3, tuned_parameters3, cv=10)
clf3.fit(x_train, y_train)

print(classification_report(y_test, clf3.predict(x_test), digits=4))
print(accuracy_score(y_test, clf3.predict(x_test)))
print(confusion_matrix(y_test, clf3.predict(x_test)))

              precision    recall  f1-score   support

           0     0.7032    0.6687    0.6855       163
           1     0.6604    0.6954    0.6774       151

    accuracy                         0.6815       314
   macro avg     0.6818    0.6820    0.6815       314
weighted avg     0.6826    0.6815    0.6816       314

0.6815286624203821
[[109  54]
 [ 46 105]]
--------------------------------------------------------------------
              precision    recall  f1-score   support

           0     0.7032    0.6687    0.6855       163
           1     0.6604    0.6954    0.6774       151

    accuracy                         0.6815       314
   macro avg     0.6818    0.6820    0.6815       314
weighted avg     0.6826    0.6815    0.6816       314

0.6815286624203821
[[109  54]
 [ 46 105]]
--------------------------------------------------------------------
              precision    recall  f1-score   support

           0     0.7032    0.6687    0.6855       163
           1   

# ***Sentimen 2***

In [ ]:
print(dataabc2.shape)
dataabc2.duplicated().sum()

(116019, 1)


17092

In [ ]:
#menghapus entri yang memiliki data duplikat
dataabc2.drop_duplicates(inplace=True)
print(dataabc2.duplicated().sum()) # no more duplicates
print(dataabc2.shape) # re-check by printing data size

0
(98927, 1)


In [ ]:
dataabc2.to_csv('dataabc3.csv')
dataabc3 = pd.read_csv('dataabc3.csv')
dataabc3.drop(columns = ['Unnamed: 0'], inplace = True)
dataabc3.head(6)

clean_text
0  semoga undang undang cipta kerja omnibus law d...
1  perjuangan minimal peningkatan pendidikan pelo...
2  markas tni mengembangkan industri militer meme...
3  potensi ekonomi digital indonesia didukung inv...
4  kemudahan investasi uu cipta kerja majukan eko...
5  jaksa agung ri st burhanuddin nmengucapkan nse...

In [ ]:
dataabc3.isnull().sum() # semua kolom

clean_text    1
dtype: int64

In [ ]:
dataabc3.dropna(inplace=True)
dataabc3.isnull().sum()

clean_text    0
dtype: int64

In [ ]:
print(dataabc3.shape)

(98926, 1)


In [ ]:
dataabc3.to_csv('dataabc4.csv')
dataabc4 = pd.read_csv('dataabc4.csv')
dataabc4.drop(columns = ['Unnamed: 0'], inplace = True)
dataabc4.head(6)

clean_text
0  semoga undang undang cipta kerja omnibus law d...
1  perjuangan minimal peningkatan pendidikan pelo...
2  markas tni mengembangkan industri militer meme...
3  potensi ekonomi digital indonesia didukung inv...
4  kemudahan investasi uu cipta kerja majukan eko...
5  jaksa agung ri st burhanuddin nmengucapkan nse...

In [ ]:
dataabc4.to_csv('testabc.csv')
dataabc4 = pd.read_csv('testabc.csv')

In [ ]:
%load_ext rpy2.ipython

In [ ]:
## ambil data yang sudah di cleaning di tahap pertama
%%R
data_clean <- read.csv('testabc.csv')
str(data_clean)

'data.frame':	98926 obs. of  2 variables:
 $ X         : int  0 1 2 3 4 5 6 7 8 9 ...
 $ clean_text: chr  "semoga undang undang cipta kerja omnibus law dipahami masyarakat masyarakat ambil transformasi ekonomi uu cipta"| __truncated__ "perjuangan minimal peningkatan pendidikan pelosok2 dg qualitas yg terukur memperbaiki sistim ekonomi khas indon"| __truncated__ "markas tni mengembangkan industri militer memenuhi kebutuhan militer negeri ekspor dampaknya gerbong ekonomi in"| __truncated__ "potensi ekonomi digital indonesia didukung investasi pemerataan aksesnya uu cipta kerja dukung pemerataan digit"| __truncated__ ...


In [ ]:
## ambil data untuk word scoring
%%R
positif <- scan("/content/drive/My Drive/TA/corpus_positif_1.txt",what="character",comment.char=";")
negatif <- scan("/content/drive/My Drive/TA/corpus_negatif_1.txt",what="character",comment.char=";")

R[write to console]: Read 1797 items

R[write to console]: Read 4081 items



In [ ]:
##jika ingin menambahkan kata yang di definisikan sendiri
%%R
kata.positif = c(positif,"cinta","bgs")
kata.negatif = c(negatif,"bangsat","busuk")

In [ ]:
%%R
install.packages("plyr")
library(stringr)

R[write to console]: Installing package into ‘/usr/local/lib/R/site-library’
(as ‘lib’ is unspecified)

R[write to console]: trying URL 'https://cran.rstudio.com/src/contrib/plyr_1.8.6.tar.gz'

R[write to console]: Content type 'application/x-gzip'
R[write to console]:  length 401191 bytes (391 KB)

R[write to console]: =
R[write to console]: =
R[write to console]: =
R[write to console]: =
R[write to console]: =
R[write to console]: =
R[write to console]: =
R[write to console]: =
R[write to console]: =
R[write to console]: =
R[write to console]: =
R[write to console]: =
R[write to console]: =
R[write to console]: =
R[write to console]: =
R[write to console]: =
R[write to console]: =
R[write to console]: =
R[write to console]: =
R[write to console]: =
R[write to console]: =
R[write to console]: =
R[write to console]: =
R[write to console]: =
R[write to console]: =
R[write to console]: =
R[write to console]: =
R[write to console]: =
R[write to console]: =
R[write to console]: =
R[write t

In [ ]:
## fungsi untuk melnalankan penilaian atau pembobotan tehadap kata-kata
%%R
score.sentiment = function(kalimat2, kata.positif, kata.negatif, .progress='none')
{
  require(plyr)
  require(stringr)
  scores = laply(kalimat2, function(kalimat, kata.positif, kata.negatif) {
    kalimat = gsub('[[:punct:]]', '', kalimat)
    kalimat = gsub('[[:cntrl:]]', '', kalimat)
    kalimat = gsub('\\d+', '', kalimat)
    kalimat = tolower(kalimat)

    list.kata = str_split(kalimat, '\\s+')
    kata2 = unlist(list.kata)
    positif.matches = match(kata2, kata.positif)
    negatif.matches = match(kata2, kata.negatif)
    positif.matches = !is.na(positif.matches)
    negatif.matches = !is.na(negatif.matches)
    score = sum(positif.matches) - (sum(negatif.matches))
    return(score)
  }, kata.positif, kata.negatif, .progress=.progress )
  scores.df = data.frame(score=scores, clean_text=kalimat2)
  return(scores.df)
}

In [ ]:
#melakukan skoring text
%%R
hasil = score.sentiment(data_clean$clean_text, kata.positif, kata.negatif)
head(hasil)

hasil$label_data<- ifelse(hasil$score<0, "Negatif","Positif")
hasil$label_data
head(hasil)

R[write to console]: Loading required package: plyr



  score
1     6
2     4
3     6
4     3
5     4
6     4
                                                                                                                                                                                                                        clean_text
1 semoga undang undang cipta kerja omnibus law dipahami masyarakat masyarakat ambil transformasi ekonomi uu cipta kerja transformasi struktural ekonomi nasional indonesia nobl perkuat digitalisasi umkm kembangkanekonomidigital
2           perjuangan minimal peningkatan pendidikan pelosok2 dg qualitas yg terukur memperbaiki sistim ekonomi khas indonesia yg pacasila butuh pemimpin2 yg hebat tdk hrs profesor paham tujuan didirikannya nkri semangat 2021
3                                                 markas tni mengembangkan industri militer memenuhi kebutuhan militer negeri ekspor dampaknya gerbong ekonomi indonesia berjalan lapangan kerja terbuka indonesia selamat bahagia
4                                   

In [ ]:
%%R
install.packages("data.table")
library(data.table)

R[write to console]: Installing package into ‘/usr/local/lib/R/site-library’
(as ‘lib’ is unspecified)

R[write to console]: trying URL 'https://cran.rstudio.com/src/contrib/data.table_1.14.0.tar.gz'

R[write to console]: Content type 'application/x-gzip'
R[write to console]:  length 5303849 bytes (5.1 MB)

R[write to console]: =
R[write to console]: =
R[write to console]: =
R[write to console]: =
R[write to console]: =
R[write to console]: =
R[write to console]: =
R[write to console]: =
R[write to console]: =
R[write to console]: =
R[write to console]: =
R[write to console]: =
R[write to console]: =
R[write to console]: =
R[write to console]: =
R[write to console]: =
R[write to console]: =
R[write to console]: =
R[write to console]: =
R[write to console]: =
R[write to console]: =
R[write to console]: =
R[write to console]: =
R[write to console]: =
R[write to console]: =
R[write to console]: =
R[write to console]: =
R[write to console]: =
R[write to console]: =
R[write to console]: =
R

In [ ]:
%%R
df_index_multiple <- (hasil)

In [ ]:
# indicate that you're running R code
%%R

# Save dataframe to CSV
write.csv(df_index_multiple, "hasil_labeling.csv", fileEncoding="UTF-8")

In [ ]:
dataabcd1 = pd.read_csv('hasil_labeling.csv')
dataabcd1.drop(columns = ['Unnamed: 0'], inplace = True)
dataabcd1.head(20)

score                                         clean_text label_data
0       6  semoga undang undang cipta kerja omnibus law d...    Positif
1       4  perjuangan minimal peningkatan pendidikan pelo...    Positif
2       6  markas tni mengembangkan industri militer meme...    Positif
3       3  potensi ekonomi digital indonesia didukung inv...    Positif
4       4  kemudahan investasi uu cipta kerja majukan eko...    Positif
5       4  jaksa agung ri st burhanuddin nmengucapkan nse...    Positif
6       1            ekonomi indonesia diyakini bangkit 2021    Positif
7       7  iklim ramah investasi kemudahan berusaha uu ci...    Positif
8       2  berkat uu cipta kerja investor global tertarik...    Positif
9       2  selamat nsmg ekonomi bangsa indonesia lg nsmg ...    Positif
10     -1  pemerintah menargetkan indonesia xc2 xa0masuk ...    Negatif
11     -1  mi instan indonesia alat transaksi seks ghana ...    Negatif
12      5  selamat 2021 tuhan merahmati hikmat kesehatan ...    Positif
13      2  teknologi informasi komunikasi tik penggerak e...    Positif
14      4  harapanku 2021 nindonesia bebas korona nsekola...    Positif
15      2  teknologi informasi komunikasi tik penggerak e...    Positif
16      1  berharap implementasi uu kebijakan target ekon...    Positif
17      0  era new umkm diharapkan sumber pertumbuhan eko...    Positif
18     -3  tangkap yg nyalain kembang api petasan gk uang...    Negatif
19      1  membangkitkan ekonomi indonesia kembangkanekon...    Positif

# ***Model Evaluation 2***

In [ ]:
dataabcd1['label_data'].replace({'Positif': 1, 'Negatif': 0}, inplace=True)

In [ ]:
dataabcd1['label_data'].value_counts()

1    65460
0    33466
Name: label_data, dtype: int64

In [ ]:
# Memisahkan kelas majority dan minority
df_maj = dataabcd1[dataabcd1.label_data==0]
df_min = dataabcd1[dataabcd1.label_data==1]

In [ ]:
# downsample minority class // metode untung resampling menyesuaikan data sebanyak data majority

from sklearn.utils import resample
df_min_dwsampled = resample(df_min,
                                 replace=True,     # sample with replacement
                                 n_samples=33466,    # to match majority class
                                 random_state=123) # reproducible results

# Combine majority class with upsampled minority class
df_dwsampled = pd.concat([df_maj, df_min_dwsampled])

# Display new class counts
df_dwsampled.label_data.value_counts()

1    33466
0    33466
Name: label_data, dtype: int64

In [ ]:
from sklearn.pipeline import Pipeline
from sklearn.feature_extraction.text import CountVectorizer, TfidfTransformer, TfidfVectorizer
from sklearn.model_selection import train_test_split, GridSearchCV

#Import classification algorithm
from sklearn.naive_bayes import MultinomialNB
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import LinearSVC
from sklearn.ensemble import RandomForestClassifier

#Import modules to calculate accuracy and confusion matrix
from sklearn.metrics import confusion_matrix, accuracy_score
from sklearn.metrics import classification_report

In [ ]:
text_clf = Pipeline([('vect', CountVectorizer()),
                     ('tfidf', TfidfTransformer()),
                     ('clf', MultinomialNB())])
tuned_parameters = {
    'vect__ngram_range': [(1, 1), (1, 2), (2, 2)],
    'tfidf__use_idf': (True, False),
    'tfidf__norm': ('l1', 'l2'),
    'clf__alpha': [1, 1e-1, 1e-2]
}

In [ ]:
text_clf1 = Pipeline([('vect', CountVectorizer()),
                     ('tfidf', TfidfTransformer()),
                     ('clf1', LinearSVC())])
tuned_parameters1 = {
    'vect__ngram_range': [(1, 2), (1, 3), (1, 4)],
    'tfidf__use_idf': (True, False),
    #'tfidf__norm': ('l1', 'l2'),
    'clf__tol': [1, 1e-1, 1e-2, 1e-3]
}

In [ ]:
text_clf2 = Pipeline([('vect', CountVectorizer()),
                     ('tfidf', TfidfTransformer()),
                     ('clf2', KNeighborsClassifier(k=3))])
tuned_parameters2 = {
}

In [ ]:
x_train, x_test, y_train, y_test = train_test_split(df_dwsampled['clean_text'], df_dwsampled['label_data'],
                                               test_size = 0.2, shuffle=True)

In [ ]:
x_train, x_test, y_train, y_test = train_test_split(df_dwsampled['clean_text'], df_dwsampled['label_data'],
                                               test_size = 0.3, shuffle=True)

clf = GridSearchCV(text_clf, tuned_parameters, cv=10)
clf.fit(x_train, y_train)

print(classification_report(y_test, clf.predict(x_test), digits=4))
print(accuracy_score(y_test, clf.predict(x_test)))
print(confusion_matrix(y_test, clf.predict(x_test)))
print('--------------------------------------------------------------------')

x_train, x_test, y_train, y_test = train_test_split(df_dwsampled['clean_text'], df_dwsampled['label_data'],
                                               test_size = 0.2, shuffle=True)

clf = GridSearchCV(text_clf, tuned_parameters, cv=10)
clf.fit(x_train, y_train)

print(classification_report(y_test, clf.predict(x_test), digits=4))
print(accuracy_score(y_test, clf.predict(x_test)))
print(confusion_matrix(y_test, clf.predict(x_test)))
print('--------------------------------------------------------------------')

x_train, x_test, y_train, y_test = train_test_split(df_dwsampled['clean_text'], df_dwsampled['label_data'],
                                               test_size = 0.1, shuffle=True)

clf = GridSearchCV(text_clf, tuned_parameters, cv=10)
clf.fit(x_train, y_train)

print(classification_report(y_test, clf.predict(x_test), digits=4))
print(accuracy_score(y_test, clf.predict(x_test)))
print(confusion_matrix(y_test, clf.predict(x_test)))

              precision    recall  f1-score   support

           0     0.7812    0.8525    0.8153      9999
           1     0.8391    0.7632    0.7994     10081

    accuracy                         0.8077     20080
   macro avg     0.8102    0.8079    0.8073     20080
weighted avg     0.8103    0.8077    0.8073     20080

0.8076693227091634
[[8524 1475]
 [2387 7694]]
--------------------------------------------------------------------
              precision    recall  f1-score   support

           0     0.7800    0.8581    0.8172      6715
           1     0.8412    0.7564    0.7966      6672

    accuracy                         0.8074     13387
   macro avg     0.8106    0.8073    0.8069     13387
weighted avg     0.8105    0.8074    0.8069     13387

0.8074251139164862
[[5762  953]
 [1625 5047]]
--------------------------------------------------------------------
              precision    recall  f1-score   support

           0     0.7847    0.8670    0.8238      3330
       

In [ ]:
x_train, x_test, y_train, y_test = train_test_split(df_dwsampled['clean_text'], df_dwsampled['label_data'],
                                               test_size = 0.3, shuffle=True)

clf1 = GridSearchCV(text_clf1, tuned_parameters1, cv=10)
clf1.fit(x_train, y_train)

print(classification_report(y_test, clf1.predict(x_test), digits=4))
print(accuracy_score(y_test, clf1.predict(x_test)))
print(confusion_matrix(y_test, clf1.predict(x_test)))
print('--------------------------------------------------------------------')

x_train, x_test, y_train, y_test = train_test_split(df_dwsampled['clean_text'], df_dwsampled['label_data'],
                                               test_size = 0.2, shuffle=True)

clf1 = GridSearchCV(text_clf1, tuned_parameters1, cv=10)
clf1.fit(x_train, y_train)

print(classification_report(y_test, clf1.predict(x_test), digits=4))
print(accuracy_score(y_test, clf1.predict(x_test)))
print(confusion_matrix(y_test, clf1.predict(x_test)))
print('--------------------------------------------------------------------')

x_train, x_test, y_train, y_test = train_test_split(df_dwsampled['clean_text'], df_dwsampled['label_data'],
                                               test_size = 0.1, shuffle=True)

clf1 = GridSearchCV(text_clf1, tuned_parameters1, cv=10)
clf1.fit(x_train, y_train)

print(classification_report(y_test, clf1.predict(x_test), digits=4))
print(accuracy_score(y_test, clf1.predict(x_test)))
print(confusion_matrix(y_test, clf1.predict(x_test)))

              precision    recall  f1-score   support

           0     0.9504    0.9471    0.9488      9998
           1     0.9477    0.9510    0.9494     10082

    accuracy                         0.9491     20080
   macro avg     0.9491    0.9490    0.9491     20080
weighted avg     0.9491    0.9491    0.9491     20080

0.9490537848605578
[[9469  529]
 [ 494 9588]]
--------------------------------------------------------------------
              precision    recall  f1-score   support

           0     0.9541    0.9547    0.9544      6641
           1     0.9554    0.9548    0.9551      6746

    accuracy                         0.9547     13387
   macro avg     0.9547    0.9547    0.9547     13387
weighted avg     0.9547    0.9547    0.9547     13387

0.9547322028833943
[[6340  301]
 [ 305 6441]]
--------------------------------------------------------------------
              precision    recall  f1-score   support

           0     0.9592    0.9527    0.9559      3404
       

In [ ]:
x_train, x_test, y_train, y_test = train_test_split(df_dwsampled['clean_text'], df_dwsampled['label_data'],
                                               test_size = 0.3, shuffle=True)

clf2 = GridSearchCV(text_clf2, tuned_parameters2, cv=10)
clf2.fit(x_train, y_train)

print(classification_report(y_test, clf2.predict(x_test), digits=4))
print(accuracy_score(y_test, clf2.predict(x_test)))
print(confusion_matrix(y_test, clf2.predict(x_test)))
print('--------------------------------------------------------------------')

x_train, x_test, y_train, y_test = train_test_split(df_dwsampled['clean_text'], df_dwsampled['label_data'],
                                               test_size = 0.2, shuffle=True)

clf2 = GridSearchCV(text_clf2, tuned_parameters2, cv=10)
clf2.fit(x_train, y_train)

print(classification_report(y_test, clf2.predict(x_test), digits=4))
print(accuracy_score(y_test, clf2.predict(x_test)))
print(confusion_matrix(y_test, clf2.predict(x_test)))
print('--------------------------------------------------------------------')

x_train, x_test, y_train, y_test = train_test_split(df_dwsampled['clean_text'], df_dwsampled['label_data'],
                                               test_size = 0.1, shuffle=True)

clf2 = GridSearchCV(text_clf2, tuned_parameters2, cv=10)
clf2.fit(x_train, y_train)

print(classification_report(y_test, clf2.predict(x_test), digits=4))
print(accuracy_score(y_test, clf2.predict(x_test)))
print(confusion_matrix(y_test, clf2.predict(x_test)))

              precision    recall  f1-score   support

           0     0.7504    0.7130    0.7312      9987
           1     0.7294    0.7653    0.7469     10093

    accuracy                         0.7393     20080
   macro avg     0.7399    0.7392    0.7391     20080
weighted avg     0.7398    0.7393    0.7391     20080

0.7392928286852589
[[7121 2866]
 [2369 7724]]
--------------------------------------------------------------------
              precision    recall  f1-score   support

           0     0.7451    0.7130    0.7287      6628
           1     0.7300    0.7608    0.7451      6759

    accuracy                         0.7371     13387
   macro avg     0.7375    0.7369    0.7369     13387
weighted avg     0.7375    0.7371    0.7370     13387

0.7371330395159483
[[4726 1902]
 [1617 5142]]
--------------------------------------------------------------------
              precision    recall  f1-score   support

           0     0.7599    0.7079    0.7330      3335
       